language: go
sudo: false

go:
  - "1.9.x"
  - "1.10.x"

before_script:
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
script:
  - golangci-lint run # run a bunch of code checkers/linters in parallel
  - go test -v -race ./... # Run all the tests with the race detector enabled
